'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Sparkles, Copy, Download, Send, Save, Instagram, Linkedin, Info, Image as ImageIcon, RefreshCw, Upload, X } from 'lucide-react';
import { useApp } from '@/lib/context/AppContext';
import { BRANDS } from '@/lib/brands';
import { DEFAULT_IMAGE_MODEL, IMAGE_MODEL_OPTIONS } from '@/lib/image-models';
import { PostPlatform } from '@/lib/types';

const IMAGE_STYLES = ['Photorealistic', 'Corporate illustration', 'Minimalist flat', 'Cinematic office', 'Tech abstract'];

function CreatePostForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { addPost, showToast, posts, updatePostStatus } = useApp();

  const editId = searchParams.get('edit');
  const dateParam = searchParams.get('date');
  const brandParam = searchParams.get('brand');

  const [selectedBrand, setSelectedBrand] = useState<string>(brandParam || 'radya');
  const [platform, setPlatform] = useState<PostPlatform>('instagram');
  const [brief, setBrief] = useState<string>('');
  const [caption, setCaption] = useState<string>('');
  const [captionSource, setCaptionSource] = useState<string>('');
  const [internalNotes, setInternalNotes] = useState<string>('Keep tone credible and compliant.');
  const [scheduledDate, setScheduledDate] = useState<string>(dateParam || new Date().toISOString().slice(0, 10));
  const [scheduledTime, setScheduledTime] = useState<string>('10:30');
  const [isGeneratingCaption, setIsGeneratingCaption] = useState<boolean>(false);
  const [isGeneratingImage, setIsGeneratingImage] = useState<boolean>(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [imageSource, setImageSource] = useState<string>('');
  const [imageStyle, setImageStyle] = useState<string>(IMAGE_STYLES[0]);
  const [imagePrompt, setImagePrompt] = useState<string>('');
  const [imageModel, setImageModel] = useState<string>(DEFAULT_IMAGE_MODEL);
  const [photoMode, setPhotoMode] = useState<'generate' | 'upload'>('generate');
  const [isUploading, setIsUploading] = useState<boolean>(false);
  const [isDragging, setIsDragging] = useState<boolean>(false);
  const [localPreview, setLocalPreview] = useState<string | null>(null);
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const [manualEditorOpen, setManualEditorOpen] = useState<boolean>(false);

  const brand = BRANDS[selectedBrand] || BRANDS.radya;

  useEffect(() => {
    if (editId) {
      const existing = posts.find((p) => p.id === editId);
      if (existing) {
        setSelectedBrand(existing.brandSlug);
        setPlatform(existing.platform);
        setBrief(existing.title);
        setCaption(existing.caption);
        setGeneratedImage(existing.mediaUrl || null);
        if (existing.mediaUrl?.includes('/uploads/')) {
          setPhotoMode('upload');
          setImageSource('upload');
        } else if (existing.mediaUrl) {
          setPhotoMode('generate');
          setImageSource('AI / existing');
        }
        const parts = (existing.scheduledAt || '').split('T');
        if (parts[0]) setScheduledDate(parts[0]);
        if (parts[1]) setScheduledTime(parts[1].substring(0, 5));
      }
    } else if (!brief) {
      setBrief(brand.defaultPrompt);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editId, posts.length]);

  const handleBrandChange = (slug: string) => {
    setSelectedBrand(slug);
    const newBrand = BRANDS[slug] || BRANDS.radya;
    setBrief((prev) => (prev ? prev : newBrand.defaultPrompt));
  };

  const handleGenerateCaption = async () => {
    if (!brief.trim()) {
      showToast('Isi brief/topik dulu.', 'warning');
      return;
    }
    setIsGeneratingCaption(true);
    try {
      const res = await fetch('/api/generate-caption', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brief, brandSlug: selectedBrand, platform }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || 'Caption gagal');
      setCaption(data.caption || '');
      setCaptionSource(data.source || '');
      showToast(`Caption generated by ${data.model || 'Gemini'} ✓`, 'success');
    } catch (err: any) {
      showToast(err?.message || 'Caption gagal', 'error');
    } finally {
      setIsGeneratingCaption(false);
    }
  };

  const handleGenerateImage = async () => {
    const visual = imagePrompt.trim();
    const prompt = visual || brief.trim();
    if (!prompt) {
      showToast('Isi brief atau prompt visual dulu.', 'warning');
      return;
    }
    setIsGeneratingImage(true);
    try {
      const res = await fetch('/api/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        // Caption final ikut sebagai konteks tematik bila prompt visual dikosongkan.
        body: JSON.stringify({
          prompt,
          caption: !visual ? caption.trim().slice(0, 800) : '',
          brandSlug: selectedBrand,
          style: imageStyle,
          model: imageModel,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || 'Image gagal');
      setGeneratedImage(data.imageUrl || null);
      setImageSource(data.source ? `${data.source}${data.model ? ` · ${data.model}` : ''}` : '');
      showToast('Foto AI dibuat dan disimpan ke Supabase Storage ✓', 'success');
    } catch (err: any) {
      showToast(err?.message || 'Image gagal', 'error');
    } finally {
      setIsGeneratingImage(false);
    }
  };

  const handleUploadImage = async (file: File) => {
    const allowed = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
    if (!allowed.includes(file.type)) {
      showToast('Format tidak didukung. Gunakan JPG, PNG, atau WebP.', 'error');
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      showToast(`Maksimal 5MB. File kamu ${(file.size / 1024 / 1024).toFixed(1)}MB.`, 'error');
      return;
    }
    // Preview lokal instan sambil upload berjalan
    if (localPreview) URL.revokeObjectURL(localPreview);
    const previewUrl = URL.createObjectURL(file);
    setLocalPreview(previewUrl);
    setIsUploading(true);
    try {
      const form = new FormData();
      form.append('file', file);
      form.append('brandSlug', selectedBrand);
      const res = await fetch('/api/upload-image', { method: 'POST', body: form });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || 'Upload gagal');
      setGeneratedImage(data.imageUrl || null);
      setImageSource(`upload · ${data.fileName || file.name}`);
      showToast('Foto diupload & disimpan ke Supabase Storage ✓', 'success');
    } catch (err: any) {
      showToast(err?.message || 'Upload gagal', 'error');
    } finally {
      setIsUploading(false);
    }
  };

  const handleRemoveImage = () => {
    setGeneratedImage(null);
    setImageSource('');
    if (localPreview) {
      URL.revokeObjectURL(localPreview);
      setLocalPreview(null);
    }
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  useEffect(() => {
    return () => {
      if (localPreview) URL.revokeObjectURL(localPreview);
    };
  }, [localPreview]);

  const handleCopyCaption = () => {
    navigator.clipboard.writeText(caption).then(() => showToast('Caption copied!', 'success')).catch(() => showToast('Caption copied!', 'success'));
  };

  const handleDownloadImage = async () => {
    if (!generatedImage) {
      showToast('Generate atau upload foto dulu.', 'warning');
      return;
    }
    try {
      const res = await fetch(generatedImage);
      const blob = await res.blob();
      const ext = blob.type.includes('svg') ? 'svg' : blob.type.includes('jpeg') || blob.type.includes('jpg') ? 'jpg' : 'png';
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${selectedBrand}_ai_${Date.now()}.${ext}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
      showToast('Foto diunduh!', 'success');
    } catch {
      const a = document.createElement('a');
      a.href = generatedImage;
      a.download = `${selectedBrand}_graphic.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
    }
  };

  const handleSave = async (status: 'draft' | 'pending_approval') => {
    if (!caption.trim()) {
      showToast('Generate / tulis caption dulu.', 'warning');
      return;
    }
    const scheduledAt = new Date(`${scheduledDate}T${scheduledTime}:00`).toISOString();

    if (editId) {
      const updated = await updatePostStatus(editId, status, null, {
        title: brief.substring(0, 80) || 'New Social Post',
        caption,
        mediaUrl: generatedImage || undefined,
        scheduledAt,
        platform,
        brandSlug: selectedBrand as any,
      });
      if (!updated) return;
      showToast(status === 'pending_approval' ? 'Post resubmitted!' : 'Draft updated di Supabase!', 'success');
    } else {
      const created = await addPost({
        brandSlug: selectedBrand as any,
        platform,
        status,
        title: brief.substring(0, 80) || 'New Social Post',
        caption,
        mediaUrl: generatedImage || undefined,
        scheduledAt,
        rejectionComment: null,
      });
      if (!created) return; // error toast sudah muncul
      showToast(status === 'pending_approval' ? 'Masuk Approval Queue ✓ (Supabase)' : 'Draft tersimpan ✓ (Supabase + muncul di Kalender)', 'success');
    }
    router.push(status === 'pending_approval' ? '/approval' : '/calendar');
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-[1fr_340px] gap-6 max-w-7xl mx-auto">
      <div className="flex flex-col gap-5">
        <div className="bg-[var(--navy-raised)] border border-[var(--navy-line)] rounded-[16px] p-6 shadow-sm flex flex-col gap-5">
          <div>
            <label className="block text-[12.5px] font-bold text-[var(--white)] uppercase tracking-wider mb-2">
              <span className="text-pink-500 mr-1">●</span> Target Brand
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {Object.values(BRANDS).map((b) => (
                <button
                  key={b.slug}
                  type="button"
                  onClick={() => handleBrandChange(b.slug)}
                  className={`flex items-center gap-2 p-2.5 rounded-[10px] border text-[12.5px] font-bold transition-all ${
                    selectedBrand === b.slug
                      ? 'bg-[rgba(23,147,232,0.16)] border-[#1793E8] text-[var(--white)]'
                      : 'bg-[var(--navy)] border-[var(--navy-line)] text-[var(--slate-300)] hover:border-[var(--slate-400)]'
                  }`}
                >
                  <span className="w-2 h-2 rounded-full bg-[var(--teal)]" />
                  <span>{b.name}</span>
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-[12.5px] font-bold text-[var(--white)] uppercase tracking-wider mb-2">Platform</label>
            <div className="grid grid-cols-2 gap-2.5">
              {(['instagram', 'linkedin'] as PostPlatform[]).map((pf) => (
                <button
                  key={pf}
                  type="button"
                  onClick={() => setPlatform(pf)}
                  className={`flex items-center justify-center gap-2 p-2.5 rounded-[10px] border text-[13px] font-bold transition-all capitalize ${
                    platform === pf
                      ? 'bg-gradient-to-r from-[rgba(23,147,232,0.2)] to-[rgba(41,182,246,0.08)] border-[#29B6F6] text-[var(--white)]'
                      : 'bg-[var(--navy)] border-[var(--navy-line)] text-[var(--slate-300)] hover:text-[var(--white)]'
                  }`}
                >
                  {pf === 'instagram' ? <Instagram className="w-4 h-4" /> : <Linkedin className="w-4 h-4" />}
                  <span>{pf}</span>
                </button>
              ))}
            </div>
          </div>

          {/* CAPTION AI */}
          <div className="border border-[#1793E8]/35 rounded-[14px] p-4 bg-gradient-to-br from-[#1793E8]/8 to-transparent">
            <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
              <span className="inline-flex items-center gap-1.5 bg-gradient-to-r from-[#1793E8] to-[#43D3A4] text-[#051021] font-extrabold text-[10.5px] uppercase tracking-wider px-2.5 py-0.5 rounded-full">
                <Sparkles className="w-3 h-3" /> AI Caption (Gemini)
              </span>
              {captionSource && <span className="text-[11px] text-[var(--slate-300)]">source: {captionSource}</span>}
            </div>
            <div className="flex gap-1.5 flex-wrap mb-2.5">
              {brand.quickPrompts.map((qp, idx) => (
                <button key={idx} type="button" onClick={() => setBrief(qp)} className="text-[11px] bg-[var(--navy-raised)] border border-[var(--navy-line)] hover:border-[#1793E8] hover:text-[#29B6F6] text-[var(--slate-300)] px-2.5 py-1 rounded-[5px] transition-all">
                  {qp}
                </button>
              ))}
            </div>
            <textarea rows={2} value={brief} onChange={(e) => setBrief(e.target.value)} placeholder="Brief / topik…" className="w-full bg-[var(--navy)] border border-[var(--navy-line)] rounded-[8px] p-3 text-[13px] text-[var(--white)] focus:outline-none focus:border-[#1793E8] mb-3" />
            <button type="button" disabled={isGeneratingCaption} onClick={handleGenerateCaption} className="w-full bg-[#1793E8] hover:bg-[#29B6F6] disabled:opacity-50 text-white font-bold py-2.5 px-4 rounded-[8px] text-[13px] flex items-center justify-center gap-2 transition-all">
              <Sparkles className="w-4 h-4" /> {isGeneratingCaption ? 'Generating caption…' : 'Generate Caption with AI'}
            </button>
            {caption && (
              <div className="mt-4 bg-[var(--navy-deep)] border border-[var(--navy-line)] rounded-[10px] p-3.5">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[11px] font-bold text-[var(--teal)] uppercase tracking-wider">Caption · {brand.name}</span>
                  <button type="button" onClick={handleCopyCaption} className="flex items-center gap-1 text-[11px] font-semibold text-[var(--slate-300)] hover:text-[var(--white)]">
                    <Copy className="w-3 h-3" /> Copy
                  </button>
                </div>
                <div className="text-[13px] text-[var(--slate-100)] leading-relaxed whitespace-pre-wrap max-h-[160px] overflow-y-auto">{caption}</div>
              </div>
            )}
            <div className="mt-3 text-center text-[12px] text-[var(--slate-400)]">
              Prefer manual?{' '}
              <button type="button" onClick={() => setManualEditorOpen(!manualEditorOpen)} className="text-[#29B6F6] font-bold underline">
                {manualEditorOpen ? 'Hide editor' : 'Toggle manual caption editor'}
              </button>
            </div>
            {manualEditorOpen && (
              <textarea rows={4} value={caption} onChange={(e) => setCaption(e.target.value)} placeholder="Tulis caption manual…" className="mt-3 w-full bg-[var(--navy)] border border-[var(--navy-line)] rounded-[8px] p-3 text-[13px] text-[var(--white)] focus:outline-none focus:border-[#1793E8]" />
            )}
          </div>

          {/* PHOTO — GENERATE AI / UPLOAD */}
          <div className="border border-[#43D3A4]/35 rounded-[14px] p-4 bg-gradient-to-br from-[#43D3A4]/8 to-transparent">
            <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
              <span className="inline-flex items-center gap-1.5 bg-gradient-to-r from-[#43D3A4] to-[#1793E8] text-[#051021] font-extrabold text-[10.5px] uppercase tracking-wider px-2.5 py-0.5 rounded-full">
                <ImageIcon className="w-3 h-3" /> Foto / Visual
              </span>
              {imageSource && <span className="text-[11px] text-[var(--slate-300)]">source: {imageSource}</span>}
            </div>
            {/* Tab switcher */}
            <div className="grid grid-cols-2 gap-2 mb-3 p-1 rounded-[10px] bg-[var(--navy)] border border-[var(--navy-line)]">
              <button
                type="button"
                onClick={() => setPhotoMode('generate')}
                className={`flex items-center justify-center gap-1.5 py-2 rounded-[7px] text-[12px] font-bold transition-all ${
                  photoMode === 'generate' ? 'bg-[#1FA579] text-white' : 'text-[var(--slate-300)] hover:text-white'
                }`}
              >
                <ImageIcon className="w-3.5 h-3.5" /> Generate AI
              </button>
              <button
                type="button"
                onClick={() => setPhotoMode('upload')}
                className={`flex items-center justify-center gap-1.5 py-2 rounded-[7px] text-[12px] font-bold transition-all ${
                  photoMode === 'upload' ? 'bg-[#1793E8] text-white' : 'text-[var(--slate-300)] hover:text-white'
                }`}
              >
                <Upload className="w-3.5 h-3.5" /> Upload Foto
              </button>
            </div>

            {photoMode === 'generate' ? (
              <>
                <textarea rows={2} value={imagePrompt} onChange={(e) => setImagePrompt(e.target.value)} placeholder={`Prompt visual (kosongkan = pakai brief + caption final sebagai konteks). cth: "modern Jakarta office team reviewing mission-critical dashboard, ${brand.name} vibe"`} className="w-full bg-[var(--navy)] border border-[var(--navy-line)] rounded-[8px] p-3 text-[13px] text-[var(--white)] focus:outline-none focus:border-[#43D3A4] mb-2.5" />
                <div className="mb-2.5">
                  <label className="block text-[11px] font-bold text-[var(--slate-300)] uppercase tracking-wider mb-1.5">
                    Model · default {DEFAULT_IMAGE_MODEL}
                  </label>
                  <select
                    value={imageModel}
                    onChange={(e) => setImageModel(e.target.value)}
                    className="w-full bg-[var(--navy)] border border-[var(--navy-line)] rounded-[8px] p-2.5 text-[13px] text-[var(--white)] focus:outline-none focus:border-[#43D3A4]"
                  >
                    {IMAGE_MODEL_OPTIONS.map((m) => (
                      <option key={m.value} value={m.value}>{m.label}</option>
                    ))}
                  </select>
                  <p className="text-[11px] text-[var(--slate-400)] mt-1">Bila model utama gagal / token habis, sistem otomatis coba model lain berurutan.</p>
                </div>
                <div className="flex gap-1.5 flex-wrap mb-3">
                  {IMAGE_STYLES.map((s) => (
                    <button key={s} type="button" onClick={() => setImageStyle(s)} className={`text-[11px] px-2.5 py-1 rounded-[5px] border transition-all ${imageStyle === s ? 'bg-[#43D3A4]/20 border-[#43D3A4] text-white font-bold' : 'bg-[var(--navy-raised)] border-[var(--navy-line)] text-[var(--slate-300)] hover:border-[#43D3A4]'}`}>
                      {s}
                    </button>
                  ))}
                </div>
                <button type="button" disabled={isGeneratingImage} onClick={handleGenerateImage} className="w-full bg-[#1FA579] hover:bg-[#43D3A4] hover:text-[#051021] disabled:opacity-50 text-white font-bold py-2.5 px-4 rounded-[8px] text-[13px] flex items-center justify-center gap-2 transition-all">
                  <ImageIcon className="w-4 h-4" /> {isGeneratingImage ? 'Generating photo (bisa 10–30 dtk)…' : 'Generate Photo with AI'}
                </button>
              </>
            ) : (
              <>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/jpeg,image/jpg,image/png,image/webp"
                  className="hidden"
                  onChange={(e) => {
                    const f = e.target.files?.[0];
                    if (f) handleUploadImage(f);
                  }}
                />
                <div
                  role="button"
                  tabIndex={0}
                  onClick={() => !isUploading && fileInputRef.current?.click()}
                  onKeyDown={(e) => {
                    if ((e.key === 'Enter' || e.key === ' ') && !isUploading) fileInputRef.current?.click();
                  }}
                  onDragOver={(e) => {
                    e.preventDefault();
                    setIsDragging(true);
                  }}
                  onDragLeave={() => setIsDragging(false)}
                  onDrop={(e) => {
                    e.preventDefault();
                    setIsDragging(false);
                    const f = e.dataTransfer.files?.[0];
                    if (f && !isUploading) handleUploadImage(f);
                  }}
                  className={`w-full rounded-[10px] border-2 border-dashed p-6 text-center cursor-pointer transition-all ${
                    isDragging ? 'border-[#1793E8] bg-[#1793E8]/10' : 'border-[var(--navy-line)] bg-[var(--navy)] hover:border-[#1793E8]'
                  } ${isUploading ? 'opacity-70 pointer-events-none' : ''}`}
                >
                  <Upload className="w-7 h-7 mx-auto mb-2 text-[#29B6F6]" />
                  <p className="text-[13px] font-bold text-[var(--white)]">
                    {isUploading ? 'Mengunggah ke Supabase Storage…' : 'Klik untuk pilih foto / drag & drop ke sini'}
                  </p>
                  <p className="text-[11.5px] text-[var(--slate-400)] mt-1">JPG, PNG, atau WebP · maksimal 5MB · tersimpan otomatis ke Supabase</p>
                </div>
                {localPreview && !generatedImage && (
                  <div className="mt-3">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={localPreview} alt="Preview upload" className="w-full rounded-[10px] border border-[var(--navy-line)] object-cover max-h-[380px] opacity-70" />
                    <p className="text-[11px] text-[var(--slate-400)] mt-1.5">Mengunggah… preview lokal, URL publik muncul setelah selesai.</p>
                  </div>
                )}
              </>
            )}

            {generatedImage && (
              <div className="mt-3">
                <div className="relative">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={generatedImage} alt="Visual post" className="w-full rounded-[10px] border border-[var(--navy-line)] object-cover max-h-[380px]" />
                  <button
                    type="button"
                    onClick={handleRemoveImage}
                    title="Hapus foto"
                    className="absolute top-2 right-2 flex items-center gap-1 bg-black/70 hover:bg-black/90 text-white text-[11px] font-bold px-2.5 py-1.5 rounded-[7px] transition-all"
                  >
                    <X className="w-3.5 h-3.5" /> Hapus
                  </button>
                </div>
                <div className="flex justify-between items-center mt-2 flex-wrap gap-2">
                  <span className="text-[11px] text-[var(--slate-400)]">Foto ini akan tersimpan ke database (media_url) &amp; tampil di Kalender/Approval.</span>
                  <div className="flex gap-2">
                    {photoMode === 'generate' && (
                      <button type="button" onClick={handleGenerateImage} className="flex items-center gap-1 text-[11px] font-bold text-[var(--slate-300)] hover:text-white">
                        <RefreshCw className="w-3 h-3" /> Regenerate
                      </button>
                    )}
                    {photoMode === 'upload' && (
                      <button type="button" onClick={() => fileInputRef.current?.click()} className="flex items-center gap-1 text-[11px] font-bold text-[var(--slate-300)] hover:text-white">
                        <Upload className="w-3 h-3" /> Ganti foto
                      </button>
                    )}
                    <button type="button" onClick={handleDownloadImage} className="flex items-center gap-1 text-[11px] font-bold text-[#43D3A4]">
                      <Download className="w-3 h-3" /> Download
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Scheduling */}
        <div className="bg-[var(--navy-raised)] border border-[var(--navy-line)] rounded-[16px] p-6 flex flex-col gap-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-[11.5px] font-bold text-[var(--slate-300)] uppercase tracking-wider mb-1.5">Scheduled Date</label>
              <input type="date" value={scheduledDate} onChange={(e) => setScheduledDate(e.target.value)} className="w-full bg-[var(--navy)] border border-[var(--navy-line)] rounded-[8px] p-2.5 text-[13px] text-[var(--white)] focus:outline-none focus:border-[#1793E8]" />
            </div>
            <div>
              <label className="block text-[11.5px] font-bold text-[var(--slate-300)] uppercase tracking-wider mb-1.5">Scheduled Time</label>
              <input type="time" value={scheduledTime} onChange={(e) => setScheduledTime(e.target.value)} className="w-full bg-[var(--navy)] border border-[var(--navy-line)] rounded-[8px] p-2.5 text-[13px] text-[var(--white)] focus:outline-none focus:border-[#1793E8]" />
            </div>
          </div>
          <div>
            <label className="block text-[11.5px] font-bold text-[var(--slate-300)] uppercase tracking-wider mb-1.5">Internal Notes</label>
            <input type="text" value={internalNotes} onChange={(e) => setInternalNotes(e.target.value)} className="w-full bg-[var(--navy)] border border-[var(--navy-line)] rounded-[8px] p-2.5 text-[13px] text-[var(--white)] focus:outline-none focus:border-[#1793E8]" />
          </div>
          <div className="flex items-center justify-between pt-4 border-t border-[var(--navy-line)] gap-3 flex-wrap">
            <button type="button" onClick={() => handleSave('draft')} className="flex items-center gap-1.5 bg-[var(--navy)] border border-[var(--navy-line)] hover:border-[var(--slate-400)] text-[var(--slate-300)] hover:text-[var(--white)] px-4 py-2 rounded-[8px] text-[12.5px] font-semibold transition-all">
              <Save className="w-3.5 h-3.5" /> Save as Draft (→ Kalender)
            </button>
            <button type="button" onClick={() => handleSave('pending_approval')} className="flex items-center gap-1.5 bg-[#1793E8] hover:bg-[#29B6F6] text-white font-bold px-5 py-2 rounded-[8px] text-[13px] transition-all">
              <Send className="w-4 h-4" /> Submit for Approval
            </button>
          </div>
        </div>
      </div>

      <aside className="bg-[var(--navy-raised)] border border-[var(--navy-line)] rounded-[16px] p-5 flex flex-col gap-3 h-fit sticky top-6">
        <div className="flex items-center gap-2 text-[13px] font-bold text-[var(--white)] mb-1">
          <Info className="w-4 h-4 text-[#1793E8]" /> <span>Brand Voice Guide</span>
        </div>
        {Object.values(BRANDS).map((b) => (
          <div key={b.slug} onClick={() => handleBrandChange(b.slug)} className={`p-3 rounded-[10px] border cursor-pointer transition-all ${selectedBrand === b.slug ? 'bg-[rgba(23,147,232,0.1)] border-[#1793E8]' : 'bg-[var(--navy)] border-[var(--navy-line)] hover:border-[var(--slate-400)]'}`}>
            <div className="font-head font-bold text-[13px] text-[var(--white)] mb-1 flex items-center justify-between">
              <span>{b.name}</span>
              {selectedBrand === b.slug && <span className="text-[10px] text-[#1793E8] font-bold uppercase">Active</span>}
            </div>
            <div className="text-[11.5px] text-[var(--slate-300)]"><strong>Audience:</strong> {b.audienceSummary}</div>
            <div className="text-[11px] text-[var(--slate-400)] mt-1.5 line-clamp-2"><strong>Tone:</strong> {b.toneContext}</div>
          </div>
        ))}
      </aside>
    </div>
  );
}

export default function CreatePage() {
  return (
    <Suspense fallback={<div className="p-8 text-center text-slate-400">Loading editor...</div>}>
      <CreatePostForm />
    </Suspense>
  );
}
